run:
	gcc palindromo.c -o main
	./main bananab

test:
	gcc palindromo.c -o main
	./main oco
	./main arara
	./main arara
	./main aibofobia
	./main matam
	./main mirim
	./main flavio
	./main davi
	./main moraski
	./main flavio
	./main caio

clean:
	rm -rfd main