encadeada:
	gcc -c lista_encadeada.c
	gcc -g main.c lista_encadeada.o -o main
	./main

sentinela:
	gcc -c lista_sentinela.c
	gcc -g main.c lista_sentinela.o -o main
	./main

flavio:
	gcc -c lista-flavio.c
	gcc -g main.c lista-flavio.o -o main_flavio
	./main
